### ISSUE TITLE
[Question] Adding new languages

### ISSUE THREAD

**Issue by beyondcompute** [zehfernandes/wordnote#11]
Hello! Thanks for the great app! I am wondering what it takes to add a new language. (Namely, I am interested in Finnish 🇫🇮 and English Wiktionary for Finnish words looks good enough in that sense for me.) Could I somehow help with that? I looked at the SQLite database format but I’m not sure what sources have you used for the current languages (do you have some scripts that convert the data into Wordnote’s format, etc.?).

Thank you! 👍

**Comment by zehfernandes** [comment]
Hey @beyondcompute.

My top priority is to add new languages. But since I used the [freedcitonaryAPI](https://github.com/meetDeveloper/freeDictionaryAPI) I don't have a parser for the Wiktionary format ready.

I'm looking to some libs that already exist and testing to see it will work, like: 
https://github.com/macdub/go-wiktionary-parse

**Comment by beyondcompute** [comment]
@zehfernandes thank you! 🙏 I do not have that strong of preferences for the source of the information. 😊
